<?php 
require_once 'BsmProfileModelGen.php';
/** 
 *  Bsm_BsmProfileModel
 *  A class for wrapping main model class.
 *  This class can be modified to add new methods.
 *  
 *  Code generated by Pokelio Codegen Module on Sun, 01 Nov 2015 10:04:36 +0100
 *  
 */ 
class Bsm_BsmProfileModel extends Bsm_BsmProfileModelGen{ 
    /**
     * Invokes the parent __construct 
     *
     */
    public function __construct() {
         parent::__construct();
     }

    /**
     * Include your own code below this point. 
     *
     */



}
