<?php 
require_once 'BsmUserModelGen.php';
/** 
 *  Bsm_BsmUserModel
 *  A class for wrapping main model class.
 *  This class can be modified to add new methods.
 *  
 *  Code generated by Pokelio Codegen Module on Sat, 31 Oct 2015 23:06:16 +0100
 *  
 */ 
class Bsm_BsmUserModel extends Bsm_BsmUserModelGen{ 
    /**
     * Invokes the parent __construct 
     *
     */
    public function __construct() {
         parent::__construct();
     }

    /**
     * Include your own code below this point. 
     *
     */

    public function updatePassword($id_user, $password){
         $parameters = array();
         $sql = "UPDATE BsmUser SET ";
         $sql.= "  password = ? ";
         $sql.= "WHERE id_user = ? ";
         $parameters[] = $password;
         $parameters[] = $id_user;
         $result = $this->execute($sql, $parameters);
         return $result;        
    }

}
